### PR TITLE
Installation refactor

### PR DESCRIPTION
**Pull request by kakposoe**
Below is a refactor of the installation script.

The idea is to clear up most of the model create methods, moving the code to its own methods.

Please see comments (by clicking commit) for a better breakdown of changes.

### CODE REVIEW

**Comment by kakposoe** [comment]
I shall make changes shortly to resolve styleci errors.

**Comment by kakposoe** [comment]
StyleCI not working

**Comment by alecritson** [comment]
Hey @kakposoe 

It's awesome that you've taken the time to do these changes, one thing I'd say that is if you want to contribute, please (for now) can you branch from dev, only because we're planning on doing a new release soon from dev and we wouldn't want to overwrite your hard work.

Once we have a release cycle going we'll make it clearer on the best ways to contribute.

Thank you!

**Comment by kakposoe** [comment]
@alecritson Thanks for the information, I will recreate any pull requests from `dev` from now. I have a few refactors incoming.

**Pull request closed without merging**
