### PR TITLE
Fix test runner and state installer

### LINKED ISSUE #312: v10 installation issues
after unsuccessful with v9 tried v10 with a fresh install of laravel 8 but getting this issues
Problem 1
    - Can only install one of: laravel/framework[v8.6.0, 7.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, v8.6.0].
    - Can only install one of: laravel/framework[7.x-dev, v8.6.0].
    - neondigital/laravel-versioning dev-master requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev].
    - getcandy/candy-api 0.10.0-beta requires neondigital/laravel-versioning dev-master -> satisfiable by neondigital/laravel-versioning[dev-master].
    - Installation request for getcandy/candy-api 0.10-beta -> satisfiable by getcandy/candy-api[0.10.0-beta].
    - Installation request for laravel/framework (locked at v8.6.0, required as ^8.0) -> satisfiable by laravel/framework[v8.6.0].
  

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by alecritson**
Fixes #312 and also gets the test runner working again.

### CODE REVIEW

**Comment by glennjacobs** [comment]
I guess we don't have a candy:update command, so for now I guess this is the route we need to take.

**Comment by alecritson** [comment]
Yeah this was meant to be a separate PR for just fixing the tests but it's got jumbled up. Consider this the full patch for the state installer and getting the test runner to run again.

**Review by glennjacobs — APPROVED** [review]

**Comment by glennjacobs** [comment]
I've approved, but don't have time to test locally. I will do over the weekend. I would suggest it's safe enough to merge.

**Comment by alecritson** [comment]
I did test locally and could install from a fresh laravel install without any hiccups so hopefully it'll be all good.

**Pull request merged**
