### PR TITLE
V1/addresses

### PR DESCRIPTION
**Pull request by glennjacobs**
Attempting to split the OpenAPI spec. So far I have done the `/addresses` path and it validates 💯

### CODE REVIEW

**Comment by glennjacobs** [comment]
Seems the referenced files break the unit tests. Need to see what can be done.

**Comment by glennjacobs** [comment]
We may need to update `openapi-psr7-validator` to v0.12 in our validator package and then reference the yaml file like

```
      $this->validator = (new ValidatorBuilder)->fromYaml($file);
```

Just a theory at this stage.

**Comment by glennjacobs** [comment]
Tests now run successfully, however, the ReadMe sync is failing.

**Comment by glennjacobs** [comment]
@alecritson I've only done the `/addresses` path so far, so need to do the other address related paths. But I wanted you to cast your eyes over it before I continue.

The OpenAPI spec is now broken down into subfolders, meaning eventually the main file will just be a list of the paths - much simpler and easier to maintain.

However, a lot of systems don't play nicely with $ref files, so I've incorporated a feature which uses speccy to resolve the spec so it's all in one file. You'll see the command in the new workflow file.

```
npm install -g speccy
speccy resolve openapi/openapi.yaml -o openapi/openapi-full.yaml
```

This is, of course, something we can use locally if we ever need the full combined spec as a single file.

Also, I've been using a Visual Studio Code plugin to assist with editing the openapi files https://github.com/42Crunch/vscode-openapi

And I've been using this to validate the spec on the command line
https://github.com/p1c2u/openapi-spec-validator

e.g. 
```
openapi-spec-validator openapi.yaml
```

The new workflow sync's the API spec automatically with ReadMe, which I think is a very nice system. It can also do the guides, so maybe we just use that?

Things to consider...

1) Do we want to document how to create the single OpenAPI file somewhere?
2) Do we want to document how to validate the spec, as shown above?
3) Are we happy with the file names? Does "openapi-full.yaml" explain itself well or would "single" make more sense?

**Comment by glennjacobs** [comment]
The other address API paths have now been added.

One further query regarding the API spec doc would be the follow...

```
    '422':
      description: Unprocessable Entity (WebDAV)
```

Do we really need the `(WebDAV)` part?

**Comment by alecritson** [comment]
> The other address API paths have now been added.
> 
> 
> 
> One further query regarding the API spec doc would be the follow...
> 
> 
> 
> ```
> 
>     '422':
> 
>       description: Unprocessable Entity (WebDAV)
> 
> ```
> 
> 
> 
> Do we really need the `(WebDAV)` part?

I think this was just added by Stoplight through their GUI

**Comment by glennjacobs** [comment]
I think I'll remove then, doesn't seem that much point to it.

**Pull request merged**
